# Generated by Django 3.1.2 on 2020-10-26 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0002_auto_20201026_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerbox',
            name='favorites',
        ),
        migrations.AddField(
            model_name='answerbox',
            name='favoriting_users',
            field=models.ManyToManyField(related_name='favorite_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answerbox',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.questionbox'),
        ),
    ]
